spring:
  profiles:
    active: local
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration
      - io.awspring.cloud.autoconfigure.core.CredentialsAutoConfiguration
      - io.awspring.cloud.autoconfigure.core.RegionProviderAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:h2:mem:rewardsdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: none
